version: 2


# Set the OS, Python version and other tools you might need

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
python:
  install:
    - requirements: src/docs/requirements.txt
sphinx:
  configuration: src/docs/source/conf.py