"""These functions are used by the plot backend to cut pieces out
 of triangulated and gridded meshes given a `bbox`. This keeps 
 irrelavent data from effecting the colormap generated by countor plots."""

from __future__ import annotations
import numpy as np
from matplotlib.tri import Triangulation
from collections.abc import Iterable
from typing import Optional
#[ ] Make a parent function for tri functions with kwarg mode={"cpu","gpu","auto"} that passes to proper function.
def tri_bbox_prep(mesh: Triangulation,
                   bbox: Iterable[float,float,float,float] | None,
                   vals: Optional[np.ndarray | None]=None
                   ) -> np.ndarray | tuple[np.ndarray, np.ndarray]:
    """Frontend for `trigridtrim()` that widens `bbox` used to trim the mesh to prevent whitespace in the plotted `bbox`.

    Parameters
    ----------
    
    mesh : matplotlib.tri.Triangulation
        The triangulated mesh that will be plotted.
    
    bbox : tuple
        typing.Iterable containing x0,y0,x1,y1 where point 0 is the bottem left and point 1 is the top right of the bounding box.
    
    vals : np.ndarray, optional
        Values that will be plotted.

    Returns
    -------
    np.ndarray | tuple[np.ndarray,np.ndarray]
        The `mesh`, and `vals` if passed, with the adjustedbbox.
    
    """
    ...
    

def trigridtrim(elemcomps: np.ndarray,nodes: np.ndarray,bbox: Iterable[float,float,float,float],vals: Optional[np.ndarray | None]=None,returnindex: bool=False) -> np.ndarray | list[np.ndarray]:
    """Funtion to cut out a portion of the elements from a unstructured triangular mesh.
    
    Parameters
    ----------
    elemcomps : np.ndarray
        (m,3) array with indexes to the nodes in the element.

    nodes : np.ndarray
        x and y coordinates of mesh with shape (n,2).

    bbox : Iterable
       Iterable containing x0,y0,x1,y1 where point 0 is the bottem left and point 1 is the top right of the bounding box.

    vals : np.ndarray, optional
        Z values of `nodes`.

    returnindex : bool
        Return the indexs used to cut the original element array.

    Returns
    -------
    np.ndarray | list
        Returns the trimmed array of `elements` or list of arrays based on kwargs.

    Note
    ----
    This differs from `trigridcut()` since the `nodes` are not removed. 

    """ 
    ...

#Creates a smaller grid from a larger grid.
def trigridcut(nodes: np.ndarray,bbox: Iterable[float,float,float,float],elemcomps: Optional[np.ndarray | None]=None,vals: Optional[np.ndarray | None]=None,returnindex: bool=False) -> np.ndarray | list[np.ndarray]:
    """Funtion to cut out a portion of the x and y coordinates from a unstructured triangular.
    
    Parameters
    ----------
    nodes : np.ndarray
        x and y coordinates of mesh with shape (n,2).
    
    bbox : Iterable
       Iterable containing x0,y0,x1,y1 where point 0 is the bottem left and point 1 is the top right of the bounding box.

    vals : np.ndarray, optional
        Z values of `nodes`.

    elemcomps : np.ndarray, optional
        (m,3) array with indexes to the `nodes` in the element. If present, `elemcomps` will be trimmed and and renumbered to match new node indexes.

    returnindex : bool
        Return the indexs used to cut the original element array.

    Returns
    -------
    np.ndarray | list
        Returns the trimmed array of `nodes` or list of arrays based on kwargs.

    Note
    ----
    This differs from `trigridtrim()` since the `nodes` themselves are removed. 

    """  
    ...

def meshgridcut(mesh: np.ndarray ,bbox: Iterable[float,float,float,float] | None,vals:np.ndarray | None=None) -> np.ndarray | tuple[np.ndarray,np.ndarray]:
    """Cuts out the x and y from a np.meshgrid. Used for stwave data.
    
    Parameters
    ----------
    mesh : np.ndarray
        Mesh generated from `np.meshgrid` where `mesh[0]` is the x coordinates and `mesh[1]` is the y coordinates.
    
    bbox : Iterable
       Iterable containing x0,y0,x1,y1 where point 0 is the bottem left and point 1 is the top right of the bounding box.

    vals : np.ndarray, optional
        Z values of nodes.

    Returns
    -------
    np.ndarray | tuple
        Returns the trimmed array of nodes or list of arrays based on kwargs.

    """
    ...